
export default function DisclaimerPage() {
    return (
        <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8 space-y-8">
            <div>
                <h1 className="text-3xl font-black tracking-tight text-foreground uppercase mb-2">Disclaimer</h1>
                <p className="text-sm text-muted-foreground uppercase font-bold tracking-wider">
                    Effective Date: {new Date().toLocaleDateString()}
                </p>
            </div>

            <div className="prose prose-sm dark:prose-invert max-w-none space-y-6 text-foreground/80">
                <section className="p-6 rounded-lg bg-card border border-border">
                    <h2 className="text-lg font-bold text-foreground mb-4 flex items-center gap-2">
                        <span className="text-orange-500">⚠️</span> General Risk Warning
                    </h2>
                    <p>
                        Trading cryptocurrencies, derivatives, and other financial instruments carries a <strong>high level of risk</strong> and may not be suitable for all investors. You could lose some or all of your initial investment. Only invest money that you can afford to lose. The high volatility of cryptocurrency markets means that prices can fluctuate wildly in very short periods.
                    </p>
                </section>

                <section>
                    <h2 className="text-lg font-bold text-foreground mb-2">No Financial Advice</h2>
                    <p>
                        The content provided on Coinpree, including but not limited to algorithmic signals, charts, indicators, and market analysis, is for <strong>informational and educational purposes only</strong>. It does not constitute financial, investment, legal, or tax advice. Coinpree is not a broker, financial advisor, or investment manager.
                    </p>
                    <p className="mt-2">
                        You should not rely on any information on this platform as a substitute for professional financial advice. Always conduct your own research (DYOR) and consult with a qualified financial advisor before making any investment decisions.
                    </p>
                </section>

                <section>
                    <h2 className="text-lg font-bold text-foreground mb-2">Accuracy of Information</h2>
                    <p>
                        While we strive to provide accurate and real-time data, Coinpree makes no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the information, products, services, or related graphics contained on the platform. Any reliance you place on such information is strictly at your own risk.
                    </p>
                </section>

                <section>
                    <h2 className="text-lg font-bold text-foreground mb-2">Algorithmic Signals</h2>
                    <p>
                        The algorithmic signals generated by Coinpree are based on historical price data and technical analysis indicators. Past performance is <strong>not indicative of future results</strong>. Algorithms cannot predict future market movements with certainty and are subject to market anomalies, data delays, and technical failures.
                    </p>
                </section>

                <section>
                    <h2 className="text-lg font-bold text-foreground mb-2">Limitation of Liability</h2>
                    <p>
                        In no event will Coinpree, its developers, affiliates, or partners be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website.
                    </p>
                </section>

                <section className="bg-primary/5 p-4 rounded-md border border-primary/10">
                    <p className="text-xs font-medium text-foreground text-center">
                        By using Coinpree, you acknowledge that you have read, understood, and agreed to this Disclaimer.
                    </p>
                </section>
            </div>
        </div>
    );
}
